name: CD
on:
  push:
    branches:
    - main

jobs:
  deploy:
    name: "Publish on PYPI"
    runs-on: ubuntu-latest
    steps:
      - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: kamuridesu
        password: ${{ secrets.PYPI_API_TOKEN }}
